name: lqrker
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7
  - pip
  - pip:
    - tensorflow==2.4.1
    - tensorflow_probability==0.12.1
    - gpflow==2.1.4
    - hydra-core==1.0.6
    - numpy
    - matplotlib
    - scipy
    - control==0.8.4
    - slycot # Might not work on Mac | https://python-control.readthedocs.io/en/0.8.4/intro.html