from .collection.nonlinearsys import KinkSpectralDensity, ParaboloidSpectralDensity, NoNameSpectralDensity, KinkSharpSpectralDensity, VanDerPolSpectralDensity, DubinsCarSpectralDensity, QuadrupedSpectralDensity, ExponentiallySuppressedPolynomialsFromData
from .collection.standard import SquaredExponentialSpectralDensity, MaternSpectralDensity


