from .collection.nonlinearsys import KinkSpectralDensity, ParaboloidSpectralDensity, NoNameSpectralDensity, KinkSharpSpectralDensity, VanDerPolSpectralDensity
from .collection.standard import SquaredExponentialSpectralDensity, MaternSpectralDensity


